[package]
name = "clock"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
crossbeam-channel = "0.5.15"
crossterm = "0.29.0"
ctrlc = "3.4.6"
reqwest = { version = "0.12.15", features = ["blocking", "json"] }
serde = { version = "1.0.219", features = ["derive"] }
tui = "0.19.0"
