[package]
name = "clock"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
crossterm = "0.29.0"
ratatui = "0.29.0"
reqwest = { version = "0.12.15", features = ["blocking", "json"] }
serde = { version = "1.0.219", features = ["derive"] }
